# =============================================================================
# Employee Management - Root Terraform Configuration
# =============================================================================
# This file wires all infrastructure modules together.
#
# Architecture:
#
#                         Internet
#                             |
#                             v
#                    AWS Network Load Balancer
#                             |
#                             v
#                    NGINX Ingress Controller
#                             |
#                             v
#                 Employee Management Service
#                             |
#                             v
#                  Employee Management Pod
#
#                         EKS Cluster
#                       /             \
#                      /               \
#          Application Node       PostgreSQL Node
#          workload=application  workload=postgres
#
# =============================================================================


# =============================================================================
# VPC
# =============================================================================

module "vpc" {
  source = "./modules/vpc"

  project_name = var.project_name
  environment  = var.environment

  vpc_cidr = var.vpc_cidr

  public_subnets = {
    public_az1 = {
      cidr              = "10.0.1.0/24"
      availability_zone = "us-east-1a"
      name              = "${var.project_name}-public-az1"
    }

    public_az2 = {
      cidr              = "10.0.2.0/24"
      availability_zone = "us-east-1b"
      name              = "${var.project_name}-public-az2"
    }
  }

  private_subnets = {
    private_az1 = {
      cidr              = "10.0.11.0/24"
      availability_zone = "us-east-1a"
      name              = "${var.project_name}-private-az1"
      nat_gateway_key   = "public_az1"
    }

    private_az2 = {
      cidr              = "10.0.12.0/24"
      availability_zone = "us-east-1b"
      name              = "${var.project_name}-private-az2"
      nat_gateway_key   = "public_az2"
    }
  }

  common_tags = local.common_tags
}


# =============================================================================
# SECURITY GROUPS
# =============================================================================

module "security_groups" {
  source = "./modules/security-groups"

  project_name = var.project_name
  environment  = var.environment

  vpc_id = module.vpc.vpc_id

  application_port = var.application_port

  common_tags = local.common_tags

  depends_on = [
    module.vpc
  ]
}


# =============================================================================
# IAM
# =============================================================================

module "iam" {
  source = "./modules/iam"

  project_name = var.project_name
  environment  = var.environment

  common_tags = local.common_tags
}


# =============================================================================
# KMS
# =============================================================================
# The KMS module expects a customer-managed key policy.
# The policy is generated by the root data source.
# =============================================================================

module "kms" {
  source = "./modules/kms"

  project_name = var.project_name
  environment  = var.environment

  deletion_window_in_days = var.kms_deletion_window_in_days

  key_policy = data.aws_iam_policy_document.eks_kms_key_policy.json

  common_tags = local.common_tags

  depends_on = [
    module.iam
  ]
}


# =============================================================================
# EKS CLUSTER
# =============================================================================

module "eks" {
  source = "./modules/eks"

  project_name = var.project_name
  environment  = var.environment

  kubernetes_version = var.kubernetes_version

  cluster_role_arn = module.iam.eks_cluster_role_arn

  # VPC module returns a map.
  # EKS module requires list(string).
  private_subnet_ids = values(module.vpc.private_subnet_ids)

  service_ipv4_cidr = var.eks_service_ipv4_cidr

  endpoint_private_access = var.eks_endpoint_private_access

  endpoint_public_access = var.eks_endpoint_public_access

  public_access_cidrs = var.eks_public_access_cidrs

  enabled_cluster_log_types = var.eks_enabled_cluster_log_types

  kms_key_arn = module.kms.key_arn

  common_tags = local.common_tags

  depends_on = [
    module.vpc,
    module.iam,
    module.kms
  ]
}


# =============================================================================
# EKS MANAGED NODE GROUPS
# =============================================================================
# Two worker nodes are created:
#
# 1. PostgreSQL node
# 2. Employee Management application node
#
# PostgreSQL:
#   label: workload=postgres
#   taint: workload=postgres:NoSchedule
#
# Application:
#   label: workload=application
#   taint: workload=application:NoSchedule
# =============================================================================

module "node_groups" {
  source = "./modules/node-groups"

  project_name = var.project_name
  environment  = var.environment

  cluster_name = module.eks.cluster_name

  node_role_arn = module.iam.eks_node_role_arn

  # VPC module returns a map.
  # Node groups module requires list(string).
  private_subnet_ids = values(module.vpc.private_subnet_ids)

  # ---------------------------------------------------------------------------
  # PostgreSQL scaling
  # ---------------------------------------------------------------------------

  postgres_desired_size = var.postgres_desired_size
  postgres_min_size     = var.postgres_min_size
  postgres_max_size     = var.postgres_max_size

  # ---------------------------------------------------------------------------
  # Application scaling
  # ---------------------------------------------------------------------------

  application_desired_size = var.application_desired_size
  application_min_size     = var.application_min_size
  application_max_size     = var.application_max_size

  # ---------------------------------------------------------------------------
  # Instance types
  # ---------------------------------------------------------------------------

  postgres_instance_types    = var.postgres_instance_types
  application_instance_types = var.application_instance_types

  # ---------------------------------------------------------------------------
  # Capacity type
  # ---------------------------------------------------------------------------

  postgres_capacity_type    = var.postgres_capacity_type
  application_capacity_type = var.application_capacity_type

  # ---------------------------------------------------------------------------
  # Disk size
  # ---------------------------------------------------------------------------

  postgres_disk_size    = var.postgres_disk_size
  application_disk_size = var.application_disk_size

  # ---------------------------------------------------------------------------
  # AMI type
  # ---------------------------------------------------------------------------

  postgres_ami_type    = var.postgres_ami_type
  application_ami_type = var.application_ami_type

  common_tags = local.common_tags

  depends_on = [
    module.eks,
    module.iam
  ]
}


# =============================================================================
# EKS ADD-ONS
# =============================================================================

module "eks_addons" {
  source = "./modules/eks-addons"

  project_name = var.project_name
  environment  = var.environment

  cluster_name = module.eks.cluster_name

  vpc_cni_version    = var.vpc_cni_version
  coredns_version    = var.coredns_version
  kube_proxy_version = var.kube_proxy_version

  common_tags = local.common_tags

  depends_on = [
    module.eks,
    module.node_groups
  ]
}


# =============================================================================
# EKS IAM OIDC PROVIDER
# =============================================================================
# Required for IAM Roles for Service Accounts (IRSA).
# Used by the EBS CSI driver.
# =============================================================================

resource "aws_iam_openid_connect_provider" "eks" {
  url = module.eks.oidc_issuer_url

  client_id_list = [
    "sts.amazonaws.com"
  ]

  tags = merge(
    local.common_tags,
    {
      Name      = "${var.project_name}-eks-oidc-provider"
      Module    = "IAM"
      Component = "EKS"
      Resource  = "IAM OIDC Provider"
      Purpose   = "IRSA for EKS workloads"
    }
  )

  depends_on = [
    module.eks
  ]
}


# =============================================================================
# EBS CSI DRIVER
# =============================================================================
# The EBS CSI module requires:
#
# - EKS OIDC provider ARN
# - OIDC issuer host/path
#
# The OIDC provider is created at the root level.
# =============================================================================

module "ebs_csi_driver" {
  source = "./modules/ebs-csi-driver"

  project_name = var.project_name
  environment  = var.environment

  cluster_name = module.eks.cluster_name

  oidc_provider_arn = aws_iam_openid_connect_provider.eks.arn

  oidc_issuer_hostpath = local.eks_oidc_issuer_hostpath

  aws_partition = data.aws_partition.current.partition

  addon_version = var.ebs_csi_addon_version

  common_tags = local.common_tags

  depends_on = [
    module.eks,
    module.node_groups,
    aws_iam_openid_connect_provider.eks
  ]
}


# =============================================================================
# NGINX INGRESS CONTROLLER
# =============================================================================
#
# Architecture:
#
# Internet
#    |
#    v
# AWS Network Load Balancer
#    |
#    v
# NGINX Ingress Controller
#    |
#    v
# Employee Management Service
#
# NGINX is scheduled on the application node using:
#
# workload=application
#
# and tolerates:
#
# workload=application:NoSchedule
#
# =============================================================================

module "nginx_ingress" {
  source = "./modules/nginx-ingress"

  project_name = var.project_name
  environment  = var.environment

  namespace    = var.nginx_namespace
  release_name = var.nginx_release_name

  helm_repository = var.nginx_helm_repository
  helm_chart      = var.nginx_helm_chart
  chart_version   = var.nginx_chart_version

  helm_timeout = var.nginx_helm_timeout

  ingress_class_name    = var.nginx_ingress_class_name
  ingress_class_default = var.nginx_ingress_class_default

  load_balancer_scheme    = var.nginx_load_balancer_scheme
  external_traffic_policy = var.nginx_external_traffic_policy

  replica_count = var.nginx_replica_count

  cpu_request    = var.nginx_cpu_request
  memory_request = var.nginx_memory_request

  cpu_limit    = var.nginx_cpu_limit
  memory_limit = var.nginx_memory_limit

  depends_on = [
    module.eks,
    module.node_groups,
    module.eks_addons
  ]
}